# Generated by Django 4.2.1 on 2023-06-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image1_post_image2_post_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='link', max_length=100),
            preserve_default=False,
        ),
    ]
